<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krypton.Components.Suite" Version="4.5.9" />
    <PackageReference Include="Krypton.Docking" Version="100.26.1.19" />
    <PackageReference Include="Krypton.Navigator" Version="100.26.1.19" />
    <PackageReference Include="Krypton.Ribbon" Version="100.26.1.19" />
    <PackageReference Include="Krypton.Toolkit" Version="100.26.1.19" />
    <PackageReference Include="Krypton.Workspace" Version="100.26.1.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
  </ItemGroup>

</Project>